CREATE VIEW "POSTVIEW" AS
SELECT POSTS.ID,
       POSTS.TITLE,
       POSTS.CONTENT,
       POSTS.SHORT_CONTENT,
       POSTS.OWNER,
       POSTS.TIMESTAMP,
       USERS.USERNAME                        AS OWNER_USERNAME,
       COALESCE(VOTE_SUMMARY.TOTAL_VOTES, 0) AS TOTAL_VOTES,
       COALESCE(VOTE_SUMMARY.UPVOTES, 0)     AS UPVOTES,
       COALESCE(VOTE_SUMMARY.DOWNVOTES, 0)   AS DOWNVOTES
FROM POSTS
         JOIN
     USERS ON POSTS.OWNER = USERS.ID
         LEFT JOIN (SELECT POST_ID,
                           COUNT(*)                                   AS TOTAL_VOTES,
                           SUM(CASE WHEN VALUE > 0 THEN 1 ELSE 0 END) AS UPVOTES,
                           SUM(CASE WHEN VALUE < 0 THEN 1 ELSE 0 END) AS DOWNVOTES
                    FROM VOTES
                    GROUP BY POST_ID) AS VOTE_SUMMARY ON POSTS.ID = VOTE_SUMMARY.POST_ID;

CREATE VIEW COMMENTVIEW AS
SELECT COMMENTS.ID,
       COMMENTS.COMMENT,
       COMMENTS.OWNER,
       COMMENTS.POST,
       COMMENTS.TIMESTAMP,
       USERS.USERNAME AS OWNER_USERNAME
FROM COMMENTS
         JOIN USERS ON COMMENTS.OWNER = USERS.ID;

