services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: votingksh
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - ./testdata:/var/lib/postgresql/data
      - ./INIT:/docker-entrypoint-initdb.d